definitions:
  Aluno:
    type: object
    properties:
      id:
        type: integer
        description: ID do aluno
      nome:
        type: string
        description: Nome do aluno
      idade:
        type: integer
        description: Idade do aluno
      nota_primeiro_semestre:
        type: number
        description: Nota do primeiro semestre
      nota_segundo_semestre:
        type: number
        description: Nota do segundo semestre
      nome_professor:
        type: string
        description: Nome do professor
      numero_sala:
        type: integer
        description: Número da sala
